# -*- coding: utf-8 -*-
"""OOPS_Concept.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOq0mI0T4x23XdFWYmNpekHQf1QymLAs

###Question 1: Define a class named Car with attributes make, model, and year. Include a method called get_info() that prints out the details of the car.
"""

class car:
  def __init__(self,make,model,year):
    self.make = make
    self.model = model
    self.year = model

  def get_info(self):
    print("The name of the compony is",self.make , "And the model is ",self.model," Which is manufactured in the year of ",self.year)

car1 = car("suzuki","swift",2013)
car1.get_info()

"""###Question 2: Create a class named Rectangle with attributes length and width. Include methods to calculate the area and perimeter of the rectangle."""

class Rectangle:
  def __init__(self,length,width):
    self.length = length
    self.width = width

  def area(self):
    print("Area of rectangle is= ",self.width*self.length)
  def perimeter(self):
    print("perimeter of rectangle is= ",2*(self.width+self.length))

rectangle = Rectangle(4,6)
rectangle.area()
rectangle.perimeter()

"""###Question 4: Create a class named BankAccount with attributes account_number, holder_name, and balance. Include methods to deposit money, withdraw money, and check the balance. Create an instance of the BankAccount class, deposit  100,withdraw 50, and then print the remaining balance."""

class BankAccount:
    def __init__(self,account_number, holder_name, balance):
      self.ac = account_number
      self.name = holder_name
      self.balance = balance

    def deposite(self,amount):
      self.balance = self.balance + amount
      print("Now we have deposited ",amount,"And current balance is", self.balance )

    def withdraw(self,amount):
      self.balance = self.balance - amount
      print("Now we have withdraw ",amount,"And current balance is", self.balance )

"""###Question 5: Define a class named Circle with attributes radius and color. Include methods to calculate the area and circumference of the circle. Create an instance of the Circle class with radius 5 and color "blue", then print its area and circumference.

"""

class Circle:
  def __init__(self,radius,color):
    self.radius=radius
    self.color=color

  def area(self):
    area = 3.14 * self.radius * self.radius
    print("Area is ",area)

  def circumference(self):
   circumference = 2* 3.14 * self.radius
   print("Area of circumference of circle is = ",circumference)

cir = Circle(5,"Blue")
cir.area()
cir.circumference()

"""###Question 6: Create a class named Book with attributes title, author, and price. Include a method called discount() that takes a percentage discount as an argument and updates the price accordingly. Create an instance of the Book class and call the discount() method with a 20% discount."""

class Book:
    def __init__(self, title, author, price):
        self.title = title
        self.author = author
        self.price = price

    def discount(self, percentage):
        self.price -= self.price * (percentage / 100)

# Creating an instance of the Book class
book = Book("The Great Gatsby", "F. Scott Fitzgerald", 20.00)

# Applying a 20% discount
book.discount(20)

# Printing the updated price
print(f"Title: {book.title}, Author: {book.author}, Price after discount: ${book.price:.2f}")

"""###Question 7: Define a class called Student with attributes name, age, and grades. Include a method called calculate_average() that computes the average grade of the student. Create an instance of the Student class with name "Alice", age 20, and grades [90, 85, 88], then print the average grade."""

class Student:
    def __init__(self, name, age, grades):
        self.name = name
        self.age = age
        self.grades = grades

    def calculate_average(self):
      average = sum(self.grades) / len(self.grades)
      print("The average is",average)

student = Student("Alice", 20, [90, 85, 88]) # Creating an instance of the Student class

average_grade = student.calculate_average() # Calculating and printing the average grade

"""###Question 8: Create a class named Rectangle with attributes length and width. Include methods to calculate the area, perimeter, and diagonal of the rectangle. Create an instance of the Rectangle class with length 4 and width 3, then print its area, perimeter, and diagonal."""

class Rectangle:
  def __init__(self,length,width):
    self.length=length
    self.width=width

  def area(self):
    area = self.length * self.width
    print("Area of rectangle is ",area)

  def perimeter(self):
    Perimeter =2*(self.length+self.width)
    print("Perimeter of rectangle is",Perimeter)

  def diagonal(self):
    Diagonal = (self.length**2 + self.width**2)
    print("Diagonals of rectangle is ",Diagonal)

rect = Rectangle(4,3)
rect.area()
rect.perimeter()
rect.diagonal()

"""###Question 9: Define a class named Person with attributes name, age, and gender. Include methods to update the age and display information about the person. Create an instance of the Person class with name "Alice", age 25, and gender "Female". Update the age to 30 and display the information about the person.

"""

class Person:
  def __init__(self,name,age,gender):
    self.name=name
    self.age=age
    self.gender=gender

  def display_info(self):
    print("Name of person is",self.name,"And his age is",self.age,"Also his gender is",self.gender)

  def update_age(self,new_age):
    self.age = new_age

person = Person("Alice",25,"Female")
person.update_age(30)
person.display_info()

"""###Question 10: Create a class named BankAccount with attributes account_number, account_holder, and balance. Include methods to deposit and withdraw money, and to display the account details. Create two instances of the BankAccount class, one for savings account and one for checking account, and perform deposit and withdrawal operations on each."""

class BankAccount:
  def __init__(self,account_number, holder_name,  balance):
    self.ac=account_number
    self.name=holder_name
    self.balance=balance
  def deposit(self,amount):
    print("The previous Balance was ",self.balance)
    self.balance = self.balance + amount
    print("Now we have deposited ",amount ,"And the current balance is ",self.balance)

  def withdraw(self,amount):
    if amount>self.balance:
      print("Insufficient Funds !!!!!!!!!!!")
      print("You can only withdraw ",self.balance)
    else:
      print("The previous Balance was ",self.balance)
      self.balance = self.balance - amount
      print("Now we have withdraw ",amount ,"And the current balance is ",self.balance)

  def check_balance(self):
    print("Name of account holder is ",self.name)
    print("Account number =",self.ac)
    print("And the current balance is =",self.balance)

saving_account=BankAccount("S0001","Pranav",50000)
current_balance=BankAccount("S0002","Asif",80000)

saving_account.deposit(30000)
current_balance.deposit(20000)

saving_account.withdraw(50000)
current_balance.withdraw(70000)

"""###Question 11: Define a class called Rectangle with attributes length and width. Include methods to calculate the area and perimeter of the rectangle, and to display its dimensions. Create an instance of the Rectangle class with length 4 and width 5, then print its area, perimeter, and dimensions."""

class Rectangle:
  def __init__(self,length,width):
    self.length = length
    self.width = width

  def area(self):
    area = self.length * self.width
    print("Area of rectangle is ",area)

  def perimeter(self):
    perimeter = 2 * (self.length + self.width)
    print("Perimeter of rectangle is ",perimeter)

  def dimention(self):
    print(f"Length: {self.length} units")  #The f tells Python to look for expressions inside {} and insert their values into the string.
    print(f"Width: {self.width} units")

rectangle = Rectangle(4,5)
rectangle.area()
rectangle.perimeter()
rectangle.dimention()

"""###Question 12: Create a class named Student with attributes name, roll_number, and grades. Include methods to add grades, calculate the average grade, and display the student's information. Create an instance of the Student class with name "John", roll number "12345", and grades [85, 90, 88]. Add another grade (95), calculate the average grade, and display the student's information."""

class Student:
    def __init__(self, name, roll_number, grades):
        self.name = name
        self.roll_number = roll_number
        self.grades = grades

    def add_grade(self, grade):
        self.grades.append(grade)

    def calculate_average(self):
        return sum(self.grades) / len(self.grades)

    def display_info(self):
        print(f"Name: {self.name}")
        print(f"Roll Number: {self.roll_number}")
        print(f"Grades: {self.grades}")
        print(f"Average Grade: {self.calculate_average():.2f}")

student = Student("John", "12345", [85, 90, 88])
student.add_grade(95)
student.display_info()

"""###Question 13: Define a class called Triangle with attributes side1, side2, and side3. Include methods to check if the triangle is valid, calculate its perimeter, area, and display its sides. Create an instance of the Triangle class with side lengths 3, 4, and 5, then check if it is valid, calculate its perimeter and area, and display its sides."""

class Triangle:
  def __init__ (self,s1,s2,s3):
    self.s1=s1
    self.s2=s2
    self.s3=s3
  def valid(self):
    if (self.s1 + self.s2 > self.s3)and (self.s1+self.s3 > self.s2) and (self.s2+self.s3 > self.s1):
      print("It is a valid Triangle =")
    else:
      print("Its is invalid !!")
  def calculate_perimeter(self):
    return self.s1 + self.s2 + self.s3

  def calculate_area(self):
      s = self.calculate_perimeter() / 2
      return (s * (s - self.s1) * (s - self.s2) * (s - self.s3)) ** 0.5

  def display_sides(self):
      print(f"Side 1: {self.s1}, Side 2: {self.s2}, Side 3: {self.s3}")

tr=Triangle(10,8,9)

tr.valid()

tr.calculate_area()

tr.calculate_perimeter()