# -*- coding: utf-8 -*-
"""Function Problems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wTSW4RLlaof4r-cWhHQhHluqZuq2hGr

Write a function that calculates the area of a rectangle given its length and width.

Description: Create a function that takes two parameters, length and width, and returns the area of the rectangle calculated using the formula: area = length * width.
"""

def rectangle_area(length, width):
    return length * width

"""Create a function that converts temperature from Celsius to Fahrenheit.

Description: Define a function that accepts a temperature value in Celsius and returns its equivalent in Fahrenheit using the conversion formula: Fahrenheit = (Celsius * 9/5) + 32.

"""

def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32

"""Write a function to find the factorial of a number.

Description: Implement a function that computes the factorial of a given number using recursion or iteration.
"""

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

"""Design a function to check if a given number is prime.

Description: Develop a function that determines whether a given number is prime or not. A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.
"""

def is_prime(number):
    if number <= 1:
        return False
    if number <= 3:
        return True
    if number % 2 == 0 or number % 3 == 0:
        return False
    i = 5
    while i * i <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6
    return True

""" Create a function that reverses a given string.

Description: Define a function that takes a string as input and returns its reverse. For example, "hello" should be returned as "olleh".
"""

def reverse_string(s):
    return s[::-1]

"""Write a function to compute the nth Fibonacci number.

Description: Implement a function that returns the nth Fibonacci number, where Fibonacci sequence starts with 0 and 1, and each subsequent number is the sum of the previous two.
"""

def fibonacci_recursive(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci_recursive(n - 1) + fibonacci_recursive(n - 2)

"""Create a function to find the largest element in a list.

Description: Develop a function that takes a list of numbers as input and returns the largest element present in the list.
"""

def find_largest_element(numbers):
    if not numbers:
        return None
    largest = numbers[0]
    for num in numbers:
        if num > largest:
            largest = num
    return largest

"""Design a function to count the number of vowels in a string.

Description: Define a function that counts and returns the number of vowels (a, e, i, o, u) present in a given string.
"""

def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0
    for char in s:
        if char in vowels:
            count += 1
    return count

"""Write a function to calculate the factorial of each number in a given list.

Description: Create a function that accepts a list of numbers as input and returns a new list containing the factorial of each number in the original list.
"""

import math

def factorial_list(numbers):
    return [math.factorial(num) for num in numbers]

"""Create a function to check if a string is a palindrome.

Description: Implement a function that checks whether a given string is a palindrome or not. A palindrome is a string that reads the same forwards and backwards.
"""

def is_palindrome(s):
    cleaned_string = ''.join(char.lower() for char in s if char.isalnum())
    return cleaned_string == cleaned_string[::-1]