# -*- coding: utf-8 -*-
"""Examples of Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196zaGwykz72O9xMH76KFlJpEdS7Gubd1

Question 1: Create a NumPy array with 5 elements initialized with zeros.
"""

import numpy as np
array = np.zeros(5)
print(array)

"""Question 2: Create a NumPy array with 3 rows and 4 columns initialized with ones."""

import numpy as np
array = np.ones((3, 4))
print(array)

"""Question 3: Create a 1D NumPy array containing numbers from 1 to 10."""

import numpy as np
array = np.arange(1, 11)
print(array)

"""Question 4: Create a 2D NumPy array with dimensions 3x3 containing numbers from 1 to 9."""

import numpy as np
array = np.arange(1, 10).reshape(3, 3)
print(array)

"""Question 5: Create a 3D NumPy array with dimensions 2x3x4 containing random integers between 0 and 9."""

import numpy as np
array = np.random.randint(0, 10, size=(2, 3, 4))
print(array)

"""Question 6: Create a NumPy array from a list containing elements [1, 2, 3, 4, 5]."""

import numpy as np
list_data = [1, 2, 3, 4, 5]
array = np.array(list_data)
print(array)

"""Question 7: Convert a tuple (6, 7, 8, 9, 10) into a NumPy array."""

import numpy as np
tuple_data = (6, 7, 8, 9, 10)
array = np.array(tuple_data)
print(array)

"""Question 8: Create a NumPy array with shape (4, 2) containing numbers from 0 to 7."""

import numpy as np
array = np.arange(8).reshape(4, 2)
print(array)

"""Question 9: Create a 3D NumPy array with shape (2, 3, 4) initialized with zeros."""

import numpy as np
array = np.zeros((2, 3, 4))
print(array)

"""Question 10: Create a 2D NumPy array with shape (3, 3) containing random floating-point numbers between 0 and 1."""

import numpy as np
array = np.random.rand(3, 3)
print(array)

"""Question 11: Create a NumPy array with shape (5,) containing numbers from 10 to 50, incrementing by 5.

"""

import numpy as np
array = np.arange(10, 51, 5)
print(array)

"""Question 12: Create a NumPy array with shape (2, 5) containing numbers from -2 to 7."""

import numpy as np
array = np.linspace(-2, 7, 10).reshape(2, 5)
print(array)

"""Question 13: Create a 1D NumPy array with shape (10,) containing numbers from 100 to 109, and change its data type to float.

"""

import numpy as np
array = np.arange(100, 110)
array_float = array.astype(float)
print(array_float)

"""Question 14: Create a 2D NumPy array with shape (3, 4) initialized with ones, and then change its data type to int."""

import numpy as np
array = np.ones((3, 4))
array_int = array.astype(int)
print(array_int)

"""Question 15: Create a 3D NumPy array with shape (2, 2, 3) initialized with specified numbers [[1, 2, 3], [4, 5, 6]], and [[7, 8, 9], [10, 11, 12]]."""

import numpy as np
array = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(array)