# -*- coding: utf-8 -*-
"""Examples of NumPy  Array .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UrO91n5nYrkRcDDrYS2AjEZfOb9gHYRP

Que 1)Given a 1D NumPy array arr_1d,extract and print the first element .
arr_1d=np.array([1,2,3,4,5])
"""

import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[0])

"""Que 2)Given a 1D NumPy array arr_1d,extract and print the first element .
arr_1d=np.array([1,2,3,4,5])
"""

import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[-3:])

"""Que 3)Given a 2D NumPy array arr_2d,extract and print the  element at the second row and third column. arr_2d=np.array([1,2,3],[4,5,6],[7,8,9])"""

import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])

"""Que 4)Given a 2D NumPy array arr_2d,extract and print first row.
 arr_2d=np.array([1,2,3],[4,5,6],[7,8,9])
"""

import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[0])

"""Question 5: Given a 2D NumPy array arr_2d, extract and print the last column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
"""

import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d[:, -1])

"""Question 6: Given a 3D NumPy array arr_3d, extract and print the element at the second matrix, third row, and third column.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
"""

import numpy as np
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d[1, 2, 2])

"""Question 7: Given a 3D NumPy array arr_3d, extract and print the first matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
"""

import numpy as np
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d[0])

"""Question 8: Given a 3D NumPy array arr_3d, extract and print the last matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
"""

import numpy as np
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d[-1])